openapi: 3.0.3
info:
  contact:
    email: backend@sii.com
  description: Next Catalog Service API (CATAS)
  title: next-catalog-service-api
  version: "0.5"
servers:
- url: http://tbd
tags:
- description: Next catalog data
  name: next-catalog-data
paths:
  /catalog/{carlineId}/modelId}:
    get:
      description: Return the entire catalog for a model.
      operationId: getCatalogDataForModel
      parameters:
      - explode: false
        in: path
        name: carlineId
        required: true
        schema:
          description: The id of the carline
          example: a4limo
          type: string
        style: simple
      - explode: true
        in: query
        name: modelId
        required: true
        schema:
          description: The id of the model
          example: 8vfanc-0-2020
          type: string
        style: form
      responses:
        "200":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/CatalogResponse'
          description: Returning a list of exterior
          headers:
            X-DataVersion:
              description: Data version
              example: mv-3131
              explode: false
              schema:
                type: string
              style: simple
        "401":
          description: Authentication information is missing or invalid
          headers:
            WWW_Authenticate:
              explode: false
              schema:
                type: string
              style: simple
        "404":
          description: The specified resource was not found.
      summary: List all equipments by model id.
      tags:
      - next-catalog-data
      x-accepts: application/json
      x-tags:
      - tag: next-catalog-data
components:
  parameters:
    carlineIdPathParameter:
      explode: false
      in: path
      name: carlineId
      required: true
      schema:
        description: The id of the carline
        example: a4limo
        type: string
      style: simple
    modelIdParameter:
      explode: true
      in: query
      name: modelId
      required: true
      schema:
        description: The id of the model
        example: 8vfanc-0-2020
        type: string
      style: form
  responses:
    NotFound:
      description: The specified resource was not found.
    UnauthorizedError:
      description: Authentication information is missing or invalid
      headers:
        WWW_Authenticate:
          explode: false
          schema:
            type: string
          style: simple
    GenericError:
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/Error'
      description: An error occurred.
  schemas:
    CatalogResponse:
      example:
        specialGroups:
        - equipmentFamilies:
          - equipments:
            - mbvId: MRADC2D
              texts:
              - null
              - null
              price: 0.0
              renderCode: MRADC2D
              name: "Räder, 10-Speichen, 6,5Jx16, Reifen 195/55 R16"
              attributes:
                key: attributes
              id: C2D
              isVisible: true
              marginable: true
              media:
              - null
              - null
              equipmentType: option
              content:
              - mbvId: tbd
                name: tbd
                evaKey: KK1
                id: tbd
              - mbvId: tbd
                name: tbd
                evaKey: KK1
                id: tbd
            - mbvId: MRADC2D
              texts:
              - null
              - null
              price: 0.0
              renderCode: MRADC2D
              name: "Räder, 10-Speichen, 6,5Jx16, Reifen 195/55 R16"
              attributes:
                key: attributes
              id: C2D
              isVisible: true
              marginable: true
              media:
              - null
              - null
              equipmentType: option
              content:
              - mbvId: tbd
                name: tbd
                evaKey: KK1
                id: tbd
              - mbvId: tbd
                name: tbd
                evaKey: KK1
                id: tbd
            name: Exterior
            id: exterior.exterior
          - equipments:
            - mbvId: MRADC2D
              texts:
              - null
              - null
              price: 0.0
              renderCode: MRADC2D
              name: "Räder, 10-Speichen, 6,5Jx16, Reifen 195/55 R16"
              attributes:
                key: attributes
              id: C2D
              isVisible: true
              marginable: true
              media:
              - null
              - null
              equipmentType: option
              content:
              - mbvId: tbd
                name: tbd
                evaKey: KK1
                id: tbd
              - mbvId: tbd
                name: tbd
                evaKey: KK1
                id: tbd
            - mbvId: MRADC2D
              texts:
              - null
              - null
              price: 0.0
              renderCode: MRADC2D
              name: "Räder, 10-Speichen, 6,5Jx16, Reifen 195/55 R16"
              attributes:
                key: attributes
              id: C2D
              isVisible: true
              marginable: true
              media:
              - null
              - null
              equipmentType: option
              content:
              - mbvId: tbd
                name: tbd
                evaKey: KK1
                id: tbd
              - mbvId: tbd
                name: tbd
                evaKey: KK1
                id: tbd
            name: Exterior
            id: exterior.exterior
          name: Infotainment/Technology
          id: infotainment
        - equipmentFamilies:
          - equipments:
            - mbvId: MRADC2D
              texts:
              - null
              - null
              price: 0.0
              renderCode: MRADC2D
              name: "Räder, 10-Speichen, 6,5Jx16, Reifen 195/55 R16"
              attributes:
                key: attributes
              id: C2D
              isVisible: true
              marginable: true
              media:
              - null
              - null
              equipmentType: option
              content:
              - mbvId: tbd
                name: tbd
                evaKey: KK1
                id: tbd
              - mbvId: tbd
                name: tbd
                evaKey: KK1
                id: tbd
            - mbvId: MRADC2D
              texts:
              - null
              - null
              price: 0.0
              renderCode: MRADC2D
              name: "Räder, 10-Speichen, 6,5Jx16, Reifen 195/55 R16"
              attributes:
                key: attributes
              id: C2D
              isVisible: true
              marginable: true
              media:
              - null
              - null
              equipmentType: option
              content:
              - mbvId: tbd
                name: tbd
                evaKey: KK1
                id: tbd
              - mbvId: tbd
                name: tbd
                evaKey: KK1
                id: tbd
            name: Exterior
            id: exterior.exterior
          - equipments:
            - mbvId: MRADC2D
              texts:
              - null
              - null
              price: 0.0
              renderCode: MRADC2D
              name: "Räder, 10-Speichen, 6,5Jx16, Reifen 195/55 R16"
              attributes:
                key: attributes
              id: C2D
              isVisible: true
              marginable: true
              media:
              - null
              - null
              equipmentType: option
              content:
              - mbvId: tbd
                name: tbd
                evaKey: KK1
                id: tbd
              - mbvId: tbd
                name: tbd
                evaKey: KK1
                id: tbd
            - mbvId: MRADC2D
              texts:
              - null
              - null
              price: 0.0
              renderCode: MRADC2D
              name: "Räder, 10-Speichen, 6,5Jx16, Reifen 195/55 R16"
              attributes:
                key: attributes
              id: C2D
              isVisible: true
              marginable: true
              media:
              - null
              - null
              equipmentType: option
              content:
              - mbvId: tbd
                name: tbd
                evaKey: KK1
                id: tbd
              - mbvId: tbd
                name: tbd
                evaKey: KK1
                id: tbd
            name: Exterior
            id: exterior.exterior
          name: Infotainment/Technology
          id: infotainment
        extColors:
        - familyName: Uni-Lacke
          id: color-type:uni
          equipmentList:
          - mbvId: MRADC2D
            texts:
            - null
            - null
            price: 0.0
            renderCode: MRADC2D
            name: "Räder, 10-Speichen, 6,5Jx16, Reifen 195/55 R16"
            attributes:
              key: attributes
            id: C2D
            isVisible: true
            marginable: true
            media:
            - null
            - null
            equipmentType: option
            content:
            - mbvId: tbd
              name: tbd
              evaKey: KK1
              id: tbd
            - mbvId: tbd
              name: tbd
              evaKey: KK1
              id: tbd
          - mbvId: MRADC2D
            texts:
            - null
            - null
            price: 0.0
            renderCode: MRADC2D
            name: "Räder, 10-Speichen, 6,5Jx16, Reifen 195/55 R16"
            attributes:
              key: attributes
            id: C2D
            isVisible: true
            marginable: true
            media:
            - null
            - null
            equipmentType: option
            content:
            - mbvId: tbd
              name: tbd
              evaKey: KK1
              id: tbd
            - mbvId: tbd
              name: tbd
              evaKey: KK1
              id: tbd
        - familyName: Uni-Lacke
          id: color-type:uni
          equipmentList:
          - mbvId: MRADC2D
            texts:
            - null
            - null
            price: 0.0
            renderCode: MRADC2D
            name: "Räder, 10-Speichen, 6,5Jx16, Reifen 195/55 R16"
            attributes:
              key: attributes
            id: C2D
            isVisible: true
            marginable: true
            media:
            - null
            - null
            equipmentType: option
            content:
            - mbvId: tbd
              name: tbd
              evaKey: KK1
              id: tbd
            - mbvId: tbd
              name: tbd
              evaKey: KK1
              id: tbd
          - mbvId: MRADC2D
            texts:
            - null
            - null
            price: 0.0
            renderCode: MRADC2D
            name: "Räder, 10-Speichen, 6,5Jx16, Reifen 195/55 R16"
            attributes:
              key: attributes
            id: C2D
            isVisible: true
            marginable: true
            media:
            - null
            - null
            equipmentType: option
            content:
            - mbvId: tbd
              name: tbd
              evaKey: KK1
              id: tbd
            - mbvId: tbd
              name: tbd
              evaKey: KK1
              id: tbd
        carlineId: a1sb
        bodyColors:
        - mbvId: MRADC2D
          texts:
          - null
          - null
          price: 0.0
          renderCode: MRADC2D
          name: "Räder, 10-Speichen, 6,5Jx16, Reifen 195/55 R16"
          attributes:
            key: attributes
          id: C2D
          isVisible: true
          marginable: true
          media:
          - null
          - null
          equipmentType: option
          content:
          - mbvId: tbd
            name: tbd
            evaKey: KK1
            id: tbd
          - mbvId: tbd
            name: tbd
            evaKey: KK1
            id: tbd
        - mbvId: MRADC2D
          texts:
          - null
          - null
          price: 0.0
          renderCode: MRADC2D
          name: "Räder, 10-Speichen, 6,5Jx16, Reifen 195/55 R16"
          attributes:
            key: attributes
          id: C2D
          isVisible: true
          marginable: true
          media:
          - null
          - null
          equipmentType: option
          content:
          - mbvId: tbd
            name: tbd
            evaKey: KK1
            id: tbd
          - mbvId: tbd
            name: tbd
            evaKey: KK1
            id: tbd
        roofColors:
        - mbvId: MRADC2D
          texts:
          - null
          - null
          price: 0.0
          renderCode: MRADC2D
          name: "Räder, 10-Speichen, 6,5Jx16, Reifen 195/55 R16"
          attributes:
            key: attributes
          id: C2D
          isVisible: true
          marginable: true
          media:
          - null
          - null
          equipmentType: option
          content:
          - mbvId: tbd
            name: tbd
            evaKey: KK1
            id: tbd
          - mbvId: tbd
            name: tbd
            evaKey: KK1
            id: tbd
        - mbvId: MRADC2D
          texts:
          - null
          - null
          price: 0.0
          renderCode: MRADC2D
          name: "Räder, 10-Speichen, 6,5Jx16, Reifen 195/55 R16"
          attributes:
            key: attributes
          id: C2D
          isVisible: true
          marginable: true
          media:
          - null
          - null
          equipmentType: option
          content:
          - mbvId: tbd
            name: tbd
            evaKey: KK1
            id: tbd
          - mbvId: tbd
            name: tbd
            evaKey: KK1
            id: tbd
        accesories:
        - mbvId: MRADC2D
          texts:
          - null
          - null
          price: 0.0
          renderCode: MRADC2D
          name: "Räder, 10-Speichen, 6,5Jx16, Reifen 195/55 R16"
          attributes:
            key: attributes
          id: C2D
          isVisible: true
          marginable: true
          media:
          - null
          - null
          equipmentType: option
          content:
          - mbvId: tbd
            name: tbd
            evaKey: KK1
            id: tbd
          - mbvId: tbd
            name: tbd
            evaKey: KK1
            id: tbd
        - mbvId: MRADC2D
          texts:
          - null
          - null
          price: 0.0
          renderCode: MRADC2D
          name: "Räder, 10-Speichen, 6,5Jx16, Reifen 195/55 R16"
          attributes:
            key: attributes
          id: C2D
          isVisible: true
          marginable: true
          media:
          - null
          - null
          equipmentType: option
          content:
          - mbvId: tbd
            name: tbd
            evaKey: KK1
            id: tbd
          - mbvId: tbd
            name: tbd
            evaKey: KK1
            id: tbd
        stealthItems:
        - mbvId: MRADC2D
          texts:
          - null
          - null
          price: 0.0
          renderCode: MRADC2D
          name: "Räder, 10-Speichen, 6,5Jx16, Reifen 195/55 R16"
          attributes:
            key: attributes
          id: C2D
          isVisible: true
          marginable: true
          media:
          - null
          - null
          equipmentType: option
          content:
          - mbvId: tbd
            name: tbd
            evaKey: KK1
            id: tbd
          - mbvId: tbd
            name: tbd
            evaKey: KK1
            id: tbd
        - mbvId: MRADC2D
          texts:
          - null
          - null
          price: 0.0
          renderCode: MRADC2D
          name: "Räder, 10-Speichen, 6,5Jx16, Reifen 195/55 R16"
          attributes:
            key: attributes
          id: C2D
          isVisible: true
          marginable: true
          media:
          - null
          - null
          equipmentType: option
          content:
          - mbvId: tbd
            name: tbd
            evaKey: KK1
            id: tbd
          - mbvId: tbd
            name: tbd
            evaKey: KK1
            id: tbd
        groups:
        - equipmentFamilies:
          - equipments:
            - mbvId: MRADC2D
              texts:
              - null
              - null
              price: 0.0
              renderCode: MRADC2D
              name: "Räder, 10-Speichen, 6,5Jx16, Reifen 195/55 R16"
              attributes:
                key: attributes
              id: C2D
              isVisible: true
              marginable: true
              media:
              - null
              - null
              equipmentType: option
              content:
              - mbvId: tbd
                name: tbd
                evaKey: KK1
                id: tbd
              - mbvId: tbd
                name: tbd
                evaKey: KK1
                id: tbd
            - mbvId: MRADC2D
              texts:
              - null
              - null
              price: 0.0
              renderCode: MRADC2D
              name: "Räder, 10-Speichen, 6,5Jx16, Reifen 195/55 R16"
              attributes:
                key: attributes
              id: C2D
              isVisible: true
              marginable: true
              media:
              - null
              - null
              equipmentType: option
              content:
              - mbvId: tbd
                name: tbd
                evaKey: KK1
                id: tbd
              - mbvId: tbd
                name: tbd
                evaKey: KK1
                id: tbd
            name: Exterior
            id: exterior.exterior
          - equipments:
            - mbvId: MRADC2D
              texts:
              - null
              - null
              price: 0.0
              renderCode: MRADC2D
              name: "Räder, 10-Speichen, 6,5Jx16, Reifen 195/55 R16"
              attributes:
                key: attributes
              id: C2D
              isVisible: true
              marginable: true
              media:
              - null
              - null
              equipmentType: option
              content:
              - mbvId: tbd
                name: tbd
                evaKey: KK1
                id: tbd
              - mbvId: tbd
                name: tbd
                evaKey: KK1
                id: tbd
            - mbvId: MRADC2D
              texts:
              - null
              - null
              price: 0.0
              renderCode: MRADC2D
              name: "Räder, 10-Speichen, 6,5Jx16, Reifen 195/55 R16"
              attributes:
                key: attributes
              id: C2D
              isVisible: true
              marginable: true
              media:
              - null
              - null
              equipmentType: option
              content:
              - mbvId: tbd
                name: tbd
                evaKey: KK1
                id: tbd
              - mbvId: tbd
                name: tbd
                evaKey: KK1
                id: tbd
            name: Exterior
            id: exterior.exterior
          name: Infotainment/Technology
          id: infotainment
        - equipmentFamilies:
          - equipments:
            - mbvId: MRADC2D
              texts:
              - null
              - null
              price: 0.0
              renderCode: MRADC2D
              name: "Räder, 10-Speichen, 6,5Jx16, Reifen 195/55 R16"
              attributes:
                key: attributes
              id: C2D
              isVisible: true
              marginable: true
              media:
              - null
              - null
              equipmentType: option
              content:
              - mbvId: tbd
                name: tbd
                evaKey: KK1
                id: tbd
              - mbvId: tbd
                name: tbd
                evaKey: KK1
                id: tbd
            - mbvId: MRADC2D
              texts:
              - null
              - null
              price: 0.0
              renderCode: MRADC2D
              name: "Räder, 10-Speichen, 6,5Jx16, Reifen 195/55 R16"
              attributes:
                key: attributes
              id: C2D
              isVisible: true
              marginable: true
              media:
              - null
              - null
              equipmentType: option
              content:
              - mbvId: tbd
                name: tbd
                evaKey: KK1
                id: tbd
              - mbvId: tbd
                name: tbd
                evaKey: KK1
                id: tbd
            name: Exterior
            id: exterior.exterior
          - equipments:
            - mbvId: MRADC2D
              texts:
              - null
              - null
              price: 0.0
              renderCode: MRADC2D
              name: "Räder, 10-Speichen, 6,5Jx16, Reifen 195/55 R16"
              attributes:
                key: attributes
              id: C2D
              isVisible: true
              marginable: true
              media:
              - null
              - null
              equipmentType: option
              content:
              - mbvId: tbd
                name: tbd
                evaKey: KK1
                id: tbd
              - mbvId: tbd
                name: tbd
                evaKey: KK1
                id: tbd
            - mbvId: MRADC2D
              texts:
              - null
              - null
              price: 0.0
              renderCode: MRADC2D
              name: "Räder, 10-Speichen, 6,5Jx16, Reifen 195/55 R16"
              attributes:
                key: attributes
              id: C2D
              isVisible: true
              marginable: true
              media:
              - null
              - null
              equipmentType: option
              content:
              - mbvId: tbd
                name: tbd
                evaKey: KK1
                id: tbd
              - mbvId: tbd
                name: tbd
                evaKey: KK1
                id: tbd
            name: Exterior
            id: exterior.exterior
          name: Infotainment/Technology
          id: infotainment
        interiorTiles:
        - familyName: Uni-Lacke
          id: color-type:uni
          equipmentList:
          - mbvId: MRADC2D
            texts:
            - null
            - null
            price: 0.0
            renderCode: MRADC2D
            name: "Räder, 10-Speichen, 6,5Jx16, Reifen 195/55 R16"
            attributes:
              key: attributes
            id: C2D
            isVisible: true
            marginable: true
            media:
            - null
            - null
            equipmentType: option
            content:
            - mbvId: tbd
              name: tbd
              evaKey: KK1
              id: tbd
            - mbvId: tbd
              name: tbd
              evaKey: KK1
              id: tbd
          - mbvId: MRADC2D
            texts:
            - null
            - null
            price: 0.0
            renderCode: MRADC2D
            name: "Räder, 10-Speichen, 6,5Jx16, Reifen 195/55 R16"
            attributes:
              key: attributes
            id: C2D
            isVisible: true
            marginable: true
            media:
            - null
            - null
            equipmentType: option
            content:
            - mbvId: tbd
              name: tbd
              evaKey: KK1
              id: tbd
            - mbvId: tbd
              name: tbd
              evaKey: KK1
              id: tbd
        - familyName: Uni-Lacke
          id: color-type:uni
          equipmentList:
          - mbvId: MRADC2D
            texts:
            - null
            - null
            price: 0.0
            renderCode: MRADC2D
            name: "Räder, 10-Speichen, 6,5Jx16, Reifen 195/55 R16"
            attributes:
              key: attributes
            id: C2D
            isVisible: true
            marginable: true
            media:
            - null
            - null
            equipmentType: option
            content:
            - mbvId: tbd
              name: tbd
              evaKey: KK1
              id: tbd
            - mbvId: tbd
              name: tbd
              evaKey: KK1
              id: tbd
          - mbvId: MRADC2D
            texts:
            - null
            - null
            price: 0.0
            renderCode: MRADC2D
            name: "Räder, 10-Speichen, 6,5Jx16, Reifen 195/55 R16"
            attributes:
              key: attributes
            id: C2D
            isVisible: true
            marginable: true
            media:
            - null
            - null
            equipmentType: option
            content:
            - mbvId: tbd
              name: tbd
              evaKey: KK1
              id: tbd
            - mbvId: tbd
              name: tbd
              evaKey: KK1
              id: tbd
      properties:
        carlineId:
          example: a1sb
          type: string
        groups:
          items:
            $ref: '#/components/schemas/EquipmentGroup'
          type: array
        extColors:
          items:
            $ref: '#/components/schemas/ExteriorColor'
          type: array
        interiorTiles:
          items:
            $ref: '#/components/schemas/InteriorTiles'
          type: array
        specialGroups:
          items:
            $ref: '#/components/schemas/EquipmentGroup'
          type: array
        bodyColors:
          items:
            $ref: '#/components/schemas/Equipment'
          type: array
        roofColors:
          items:
            $ref: '#/components/schemas/Equipment'
          type: array
        stealthItems:
          items:
            $ref: '#/components/schemas/Equipment'
          type: array
        accesories:
          items:
            $ref: '#/components/schemas/Equipment'
          type: array
      type: object
    EquipmentGroup:
      example:
        equipmentFamilies:
        - equipments:
          - mbvId: MRADC2D
            texts:
            - null
            - null
            price: 0.0
            renderCode: MRADC2D
            name: "Räder, 10-Speichen, 6,5Jx16, Reifen 195/55 R16"
            attributes:
              key: attributes
            id: C2D
            isVisible: true
            marginable: true
            media:
            - null
            - null
            equipmentType: option
            content:
            - mbvId: tbd
              name: tbd
              evaKey: KK1
              id: tbd
            - mbvId: tbd
              name: tbd
              evaKey: KK1
              id: tbd
          - mbvId: MRADC2D
            texts:
            - null
            - null
            price: 0.0
            renderCode: MRADC2D
            name: "Räder, 10-Speichen, 6,5Jx16, Reifen 195/55 R16"
            attributes:
              key: attributes
            id: C2D
            isVisible: true
            marginable: true
            media:
            - null
            - null
            equipmentType: option
            content:
            - mbvId: tbd
              name: tbd
              evaKey: KK1
              id: tbd
            - mbvId: tbd
              name: tbd
              evaKey: KK1
              id: tbd
          name: Exterior
          id: exterior.exterior
        - equipments:
          - mbvId: MRADC2D
            texts:
            - null
            - null
            price: 0.0
            renderCode: MRADC2D
            name: "Räder, 10-Speichen, 6,5Jx16, Reifen 195/55 R16"
            attributes:
              key: attributes
            id: C2D
            isVisible: true
            marginable: true
            media:
            - null
            - null
            equipmentType: option
            content:
            - mbvId: tbd
              name: tbd
              evaKey: KK1
              id: tbd
            - mbvId: tbd
              name: tbd
              evaKey: KK1
              id: tbd
          - mbvId: MRADC2D
            texts:
            - null
            - null
            price: 0.0
            renderCode: MRADC2D
            name: "Räder, 10-Speichen, 6,5Jx16, Reifen 195/55 R16"
            attributes:
              key: attributes
            id: C2D
            isVisible: true
            marginable: true
            media:
            - null
            - null
            equipmentType: option
            content:
            - mbvId: tbd
              name: tbd
              evaKey: KK1
              id: tbd
            - mbvId: tbd
              name: tbd
              evaKey: KK1
              id: tbd
          name: Exterior
          id: exterior.exterior
        name: Infotainment/Technology
        id: infotainment
      properties:
        id:
          example: infotainment
          type: string
        name:
          description: Name of the mbv lasche
          example: Infotainment/Technology
          type: string
        equipmentFamilies:
          items:
            $ref: '#/components/schemas/EquipmentFamily'
          type: array
      type: object
    ExteriorColor:
      example:
        familyName: Uni-Lacke
        id: color-type:uni
        equipmentList:
        - mbvId: MRADC2D
          texts:
          - null
          - null
          price: 0.0
          renderCode: MRADC2D
          name: "Räder, 10-Speichen, 6,5Jx16, Reifen 195/55 R16"
          attributes:
            key: attributes
          id: C2D
          isVisible: true
          marginable: true
          media:
          - null
          - null
          equipmentType: option
          content:
          - mbvId: tbd
            name: tbd
            evaKey: KK1
            id: tbd
          - mbvId: tbd
            name: tbd
            evaKey: KK1
            id: tbd
        - mbvId: MRADC2D
          texts:
          - null
          - null
          price: 0.0
          renderCode: MRADC2D
          name: "Räder, 10-Speichen, 6,5Jx16, Reifen 195/55 R16"
          attributes:
            key: attributes
          id: C2D
          isVisible: true
          marginable: true
          media:
          - null
          - null
          equipmentType: option
          content:
          - mbvId: tbd
            name: tbd
            evaKey: KK1
            id: tbd
          - mbvId: tbd
            name: tbd
            evaKey: KK1
            id: tbd
      properties:
        id:
          example: color-type:uni
          type: string
        familyName:
          example: Uni-Lacke
          type: string
        equipmentList:
          items:
            $ref: '#/components/schemas/Equipment'
          type: array
      type: object
    InteriorTiles:
      example:
        familyName: Uni-Lacke
        id: color-type:uni
        equipmentList:
        - mbvId: MRADC2D
          texts:
          - null
          - null
          price: 0.0
          renderCode: MRADC2D
          name: "Räder, 10-Speichen, 6,5Jx16, Reifen 195/55 R16"
          attributes:
            key: attributes
          id: C2D
          isVisible: true
          marginable: true
          media:
          - null
          - null
          equipmentType: option
          content:
          - mbvId: tbd
            name: tbd
            evaKey: KK1
            id: tbd
          - mbvId: tbd
            name: tbd
            evaKey: KK1
            id: tbd
        - mbvId: MRADC2D
          texts:
          - null
          - null
          price: 0.0
          renderCode: MRADC2D
          name: "Räder, 10-Speichen, 6,5Jx16, Reifen 195/55 R16"
          attributes:
            key: attributes
          id: C2D
          isVisible: true
          marginable: true
          media:
          - null
          - null
          equipmentType: option
          content:
          - mbvId: tbd
            name: tbd
            evaKey: KK1
            id: tbd
          - mbvId: tbd
            name: tbd
            evaKey: KK1
            id: tbd
      properties:
        id:
          example: color-type:uni
          type: string
        familyName:
          example: Uni-Lacke
          type: string
        equipmentList:
          items:
            $ref: '#/components/schemas/Equipment'
          type: array
      type: object
    Accessories:
      properties:
        id:
          example: color-type:uni
          type: string
        families:
          items:
            $ref: '#/components/schemas/EquipmentFamily'
          type: array
      type: object
    EquipmentFamily:
      example:
        equipments:
        - mbvId: MRADC2D
          texts:
          - null
          - null
          price: 0.0
          renderCode: MRADC2D
          name: "Räder, 10-Speichen, 6,5Jx16, Reifen 195/55 R16"
          attributes:
            key: attributes
          id: C2D
          isVisible: true
          marginable: true
          media:
          - null
          - null
          equipmentType: option
          content:
          - mbvId: tbd
            name: tbd
            evaKey: KK1
            id: tbd
          - mbvId: tbd
            name: tbd
            evaKey: KK1
            id: tbd
        - mbvId: MRADC2D
          texts:
          - null
          - null
          price: 0.0
          renderCode: MRADC2D
          name: "Räder, 10-Speichen, 6,5Jx16, Reifen 195/55 R16"
          attributes:
            key: attributes
          id: C2D
          isVisible: true
          marginable: true
          media:
          - null
          - null
          equipmentType: option
          content:
          - mbvId: tbd
            name: tbd
            evaKey: KK1
            id: tbd
          - mbvId: tbd
            name: tbd
            evaKey: KK1
            id: tbd
        name: Exterior
        id: exterior.exterior
      properties:
        id:
          example: exterior.exterior
          type: string
        name:
          example: Exterior
          type: string
        equipments:
          items:
            $ref: '#/components/schemas/Equipment'
          type: array
      type: object
    Equipment:
      example:
        mbvId: MRADC2D
        texts:
        - null
        - null
        price: 0.0
        renderCode: MRADC2D
        name: "Räder, 10-Speichen, 6,5Jx16, Reifen 195/55 R16"
        attributes:
          key: attributes
        id: C2D
        isVisible: true
        marginable: true
        media:
        - null
        - null
        equipmentType: option
        content:
        - mbvId: tbd
          name: tbd
          evaKey: KK1
          id: tbd
        - mbvId: tbd
          name: tbd
          evaKey: KK1
          id: tbd
      properties:
        id:
          description: The eva key. Display id
          example: C2D
          type: string
        mbvId:
          description: The mbv id. Internal id
          example: MRADC2D
          type: string
        renderCode:
          description: The render code.
          example: MRADC2D
          type: string
        name:
          description: The name
          example: "Räder, 10-Speichen, 6,5Jx16, Reifen 195/55 R16"
          type: string
        equipmentType:
          $ref: '#/components/schemas/EquipmentType'
        isVisible:
          description: The okapi is visible flag. Not used in nemo but in newDcc
          example: true
          type: boolean
        marginable:
          description: Not used in nemo but in newDcc
          type: boolean
        price:
          description: The mbv list price. Standards never have prices
          example: 0.0
          type: number
        texts:
          items:
            $ref: '#/components/schemas/Texts'
          type: array
        media:
          items:
            $ref: '#/components/schemas/Media'
          type: array
        attributes:
          additionalProperties:
            type: string
            example: null
          type: object
        content:
          description: |
            The content of the package.
          items:
            $ref: '#/components/schemas/PackageContent'
          type: array
      required:
      - equipmentType
      - id
      - name
      type: object
    EquipmentType:
      enum:
      - exterior
      - interior
      - standard
      - option
      example: option
      type: string
    PackageContent:
      example:
        mbvId: tbd
        name: tbd
        evaKey: KK1
        id: tbd
      properties:
        name:
          description: name
          example: tbd
          type: string
        id:
          description: The id
          example: tbd
          type: string
        mbvId:
          description: the mbv id
          example: tbd
          type: string
        evaKey:
          example: KK1
          type: string
      required:
      - id
      - mbvId
      - name
      type: object
    Texts:
      additionalProperties:
        example: "{\"ak_headline\":\"Räder, 10-Speichen, 6,5Jx16, Reifen 195/55 R16\"\
          ,\"ak_remarks\":\"<p><b>Hinweis</b>: Serie A1 Sportback S line 25 TFSI und\
          \ 30 TFSI; A1 Sportback 35 TFSI</p>\",\"importname\":\"Räder, 10-Speichen,\
          \ 6,5Jx16, Reifen modellspezifisch\",\"tyre-label-0\":\"https://eprel.ec.europa.eu/api/products/tyres/380866/labels?noRedirect=false&format=SVG&supplier_label=false\"\
          ,\"tyre-pdf-0\":\"https://eprel.ec.europa.eu/api/products/tyres/380866/fiches?noRedirect=false&language=DE\"\
          ,\"tyre-label-1\":\"https://eprel.ec.europa.eu/api/products/tyres/531164/labels?noRedirect=false&format=SVG&supplier_label=false\"\
          ,\"tyre-pdf-1\":\"https://eprel.ec.europa.eu/api/products/tyres/531164/fiches?noRedirect=false&language=DE\"\
          }"
        type: string
      type: object
    Media:
      additionalProperties:
        example: "{\"type\":\"wheel_image_small\",\"url\":\"//pre-mediaservice.audi.com/media/cdb/data/c27c5d15-2f86-4b22-aa2c-a6c1d038eac8.jpg\"\
          ,\"mimeType\":\"image/jpeg\",\"width\":200,\"height\":200}"
        type: string
      type: object
    AttributeInfo:
      additionalProperties:
        type: string
        example: null
      type: object
    ModelFilter:
      additionalProperties:
        type: string
      example:
        Antrieb: "-"
        Getriebeart: S
        Motorart: "0"
      type: object
    Error:
      properties:
        code:
          type: string
        message:
          type: string
      required:
      - code
      - message
      type: object
  securitySchemes:
    ApiKeyAuth:
      in: header
      name: X-API-KEY
      type: apiKey
